/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class Repository {
  root: string;
  isMonorepo: boolean;
  static detectJS(path?: string | undefined | null): Repository;
}
