/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function hello(): string;
export function findRoot(path: string): string;
export class Repository {
  root: string;
  isMonorepo: boolean;
  static detectJS(path?: string | undefined | null): Repository;
}
