name: Turborepo Library Release

on:
  workflow_dispatch:

jobs:
  build:
    defaults:
      run:
        shell: bash -leo pipefail {0}

    strategy:
      fail-fast: false
      matrix:
        settings:
          # - host: macos-latest
          #   target: "aarch64-apple-darwin"
          # - host: macos-latest
          #   target: "x86_64-apple-darwin"
          - host: ubuntu-latest
            target: "aarch64-unknown-linux-gnu"
            container: ghcr.io/napi-rs/napi-rs/nodejs-rust:stable-2023-09-17-alpine
            setup: |
              rustup toolchain install "${RUST_TOOLCHAIN}" &&
              rustup default "${RUST_TOOLCHAIN}" &&
              rustup target add aarch64-unknown-linux-gnu &&
              export CC_aarch64_unknown_linux_gnu=/usr/aarch64-unknown-linux-gnu/bin/aarch64-unknown-linux-gnu-gcc
          # - host: ubuntu-latest
          #   target: "x86_64-unknown-linux-gnu"
          - host: windows-latest
            target: "aarch64-pc-windows-msvc"
          - host: windows-latest
            target: "x86_64-pc-windows-msvc"

    runs-on: ${{ matrix.settings.host }}
    container:
      image: ${{ matrix.settings.container }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          targets: ${{ matrix.settings.target }}
          skip-install: ${{ matrix.settings.container }}

      - name: Setup Node
        uses: ./.github/actions/setup-node
        with:
          enable-corepack: false

      - name: Setup toolchain
        run: ${{ matrix.settings.setup }}
        if: ${{ matrix.settings.setup }}

      - name: Build native library
        run: |
          cd packages/turbo-repository
          mkdir -p js/dist
          pnpm build:release --target=${{ matrix.settings.target }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: turbo-library-${{ matrix.settings.target }}
          path: packages/turbo-repository/native
